[book]
authors = ["Schell Scivally"]
language = "en"
src = "src"
title = "Zyghost"

[preprocessor.variables.variables]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["extra.css", "FontAwesome/css/font-awesome.css"]
default-theme = "rust"
hash-files = false

[output.html.fold]
enable = true
level = 0

# [output.linkcheck]
