[book]
authors = ["Schell Scivally"]
language = "en"
multilingual = false
src = "src"
title = "Zyghost"

[preprocessor.variables.variables]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["extra.css"]
default-theme = "rust"

[output.linkcheck]
