flags: {}
packages:
- .
- location:
    git: https://github.com/schell/milkshake.git
    commit: d28abd4a9146ee72aebb4c069b4fa0442c141f05
  extra-dep: true

resolver: lts-7.14
extra-deps:
- pretty-simple-2.0.0.0
